name: React Thread Runner NPM Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          node --version
          npm --version
          npm ci
          npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          echo "_auth=$NPM_PUBLISH_KEY" >> .npmrc
          echo "email=$NPM_EMAIL" >> .npmrc
          echo "always-auth=true" >> .npmrc
          npm ci
          npm run build
          npm version --no-git-tag-version prerelease
          npm publish
        env:
          NPM_PUBLISH_KEY: ${{ secrets.NPM_PUBLISH_KEY }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}